Repository ucsb-cs156-f24/proj-rec-f24-05, pull requests merged in 2024-11, with the labels that each got.

#48 Add Entity, Repository and DB Migration files for RequestType
  src/main/java/edu/ucsb/cs156/rec/entities/RequestType.java
  src/main/java/edu/ucsb/cs156/rec/repositories/RequestTypeRepository.java
  src/main/resources/db/migration/changes/RequestTypes.json
Labels: Ready-For-Staff

#53 RequestType Post + Tests
  .github/workflows/58-javadoc-pr.yml
  src/main/java/edu/ucsb/cs156/rec/controllers/ApiController.java
  src/main/java/edu/ucsb/cs156/rec/controllers/RequestTypesController.java
  src/main/java/edu/ucsb/cs156/rec/entities/RequestType.java
  src/main/java/edu/ucsb/cs156/rec/errors/DuplicateArgumentException.java
  src/main/java/edu/ucsb/cs156/rec/repositories/RequestTypeRepository.java
  src/main/resources/db/migration/changes/RequestTypes.json
  src/test/java/edu/ucsb/cs156/rec/controllers/RequestTypesControllerTests.java
Labels: 10, Merge Candidate-CI

#60 RequestType Put + Tests
  src/main/java/edu/ucsb/cs156/rec/controllers/RequestTypesController.java
  src/test/java/edu/ucsb/cs156/rec/controllers/RequestTypesControllerTests.java
Labels: 10, Merge Candidate-CI

#56 Add GET all operation for RequestType table
  src/main/java/edu/ucsb/cs156/rec/controllers/RequestTypesController.java
  src/test/java/edu/ucsb/cs156/rec/controllers/RequestTypesControllerTests.java
Labels: Ready-For-Staff

#58 added fixtures, utils&tests, and table&tests for requestType
  .github/workflows/82-kanban-slack-update.yml
  frontend/src/main/components/RequestTypes/RequestTypeTable.js
  frontend/src/stories/components/RequestTypes/RequestTypeTable.stories.js
  frontend/src/tests/components/RequestTypes/RequestTypeTable.test.js
Labels: 10, Merge Candidate-CI

#59 Added GET by id operation for RequestType
  src/main/java/edu/ucsb/cs156/rec/controllers/RequestTypesController.java
  src/test/java/edu/ucsb/cs156/rec/controllers/RequestTypesControllerTests.java
Labels: 10

#63 Added Entity + Repository Files for RecommendationRequest
  src/main/java/edu/ucsb/cs156/rec/ExampleApplication.java
  src/main/java/edu/ucsb/cs156/rec/controllers/RequestTypesController.java
  src/main/java/edu/ucsb/cs156/rec/entities/RecommendationRequest.java
  src/main/java/edu/ucsb/cs156/rec/repositories/RecommendationRequestRepository.java
Labels: 10

#72 Add Migration For Recommendation Requests
  src/main/resources/db/migration/changes/RecommendationRequests.json
Labels: 5, Merge Candidate-CI

#67 Added DELETE operation for RequestType
  src/main/java/edu/ucsb/cs156/rec/controllers/RequestTypesController.java
  src/test/java/edu/ucsb/cs156/rec/controllers/RequestTypesControllerTests.java
Labels: 10, Merge Candidate-CI

#74 Added dropdown for Request Type
  .env.SAMPLE
  frontend/src/fixtures/requestFixtures.js
  frontend/src/main/components/RequestTypeDropdown/RequestTypeDropdown.js
  frontend/src/main/utils/sortHelper.js
  frontend/src/stories/components/RequestTypeDropdown/RequestTypeDropdown.stories.js
  frontend/src/tests/components/RequestTypeDropdown/RequestTypeDropdown.test.js
  frontend/src/tests/utils/sortHelper.test.js
  src/main/resources/db/migration/changes/RequestTypes.json
Labels: 10

#78 Removed files for tables that are not needed in the app
  frontend/src/App.js
  frontend/src/fixtures/restaurantFixtures.js
  frontend/src/fixtures/ucsbDatesFixtures.js
  frontend/src/main/components/Nav/AppNavbar.js
  frontend/src/main/components/Restaurants/RestaurantForm.js
  frontend/src/main/components/Restaurants/RestaurantTable.js
  frontend/src/main/components/UCSBDates/UCSBDateForm.js
  frontend/src/main/components/UCSBDates/UCSBDatesTable.js
  frontend/src/main/pages/Restaurants/RestaurantCreatePage.js
  frontend/src/main/pages/Restaurants/RestaurantEditPage.js
  frontend/src/main/pages/Restaurants/RestaurantIndexPage.js
  frontend/src/main/pages/UCSBDates/UCSBDatesCreatePage.js
  frontend/src/main/pages/UCSBDates/UCSBDatesEditPage.js
  frontend/src/main/pages/UCSBDates/UCSBDatesIndexPage.js
  frontend/src/main/utils/UCSBDateUtils.js
  frontend/src/main/utils/restaurantUtils.js
  frontend/src/stories/components/Restaurants/RestaurantForm.stories.js
  frontend/src/stories/components/Restaurants/RestaurantTable.stories.js
  frontend/src/stories/components/UCSBDates/UCSBDateForm.stories.js
  frontend/src/stories/components/UCSBDates/UCSBDatesTable.stories.js
  frontend/src/stories/pages/Restaurants/RestaurantCreatePage.stories.js
  frontend/src/stories/pages/Restaurants/RestaurantEditPage.stories.js
  frontend/src/stories/pages/Restaurants/RestaurantIndexPage.stories.js
  frontend/src/stories/pages/UCSBDates/UCSBDatesCreatePage.stories.js
  frontend/src/stories/pages/UCSBDates/UCSBDatesEditPage.stories.js
  frontend/src/stories/pages/UCSBDates/UCSBDatesIndexPage.stories.js
  frontend/src/tests/components/Nav/AppNavbar.test.js
  frontend/src/tests/components/Restaurants/RestaurantForm.test.js
  frontend/src/tests/components/Restaurants/RestaurantTable.test.js
  frontend/src/tests/components/UCSBDates/UCSBDateForm.test.js
  frontend/src/tests/components/UCSBDates/UCSBDatesTable.test.js
  frontend/src/tests/pages/Restaurants/RestaurantCreatePage.test.js
  frontend/src/tests/pages/Restaurants/RestaurantEditPage.test.js
  frontend/src/tests/pages/Restaurants/RestaurantIndexPage.test.js
  frontend/src/tests/pages/UCSBDates/UCSBDatesCreatePage.test.js
  frontend/src/tests/pages/UCSBDates/UCSBDatesEditPage.test.js
  frontend/src/tests/pages/UCSBDates/UCSBDatesIndexPage.test.js
  frontend/src/tests/utils/UCSBDateUtils.test.js
  src/main/java/edu/ucsb/cs156/rec/controllers/RestaurantsController.java
  src/main/java/edu/ucsb/cs156/rec/controllers/UCSBDatesController.java
  src/main/java/edu/ucsb/cs156/rec/controllers/UCSBDiningCommonsController.java
  src/main/java/edu/ucsb/cs156/rec/entities/Restaurant.java
  src/main/java/edu/ucsb/cs156/rec/entities/UCSBDate.java
  src/main/java/edu/ucsb/cs156/rec/entities/UCSBDiningCommons.java
  src/main/java/edu/ucsb/cs156/rec/repositories/RestaurantRepository.java
  src/main/java/edu/ucsb/cs156/rec/repositories/UCSBDateRepository.java
  src/main/java/edu/ucsb/cs156/rec/repositories/UCSBDiningCommonsRepository.java
  src/main/resources/db/migration/changes/Restaurants.json
  src/main/resources/db/migration/changes/UCSBDates.json
  src/main/resources/db/migration/changes/UCSBDiningCommons.json
  src/test/java/edu/ucsb/cs156/rec/controllers/RequestTypesControllerTests.java
  src/test/java/edu/ucsb/cs156/rec/controllers/RestaurantsControllerTests.java
  src/test/java/edu/ucsb/cs156/rec/controllers/UCSBDatesControllerTests.java
  src/test/java/edu/ucsb/cs156/rec/controllers/UCSBDiningCommonsControllerTests.java
  src/test/java/edu/ucsb/cs156/rec/integration/RestaurantIT.java
  src/test/java/edu/ucsb/cs156/rec/web/RestaurantWebIT.java
  src/test/java/edu/ucsb/cs156/rec/web/SwaggerWebIT.java
Labels: 5, Merge Candidate-CI, Ready-For-Staff
